package com.example.mis4203movilvinilosjpc.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFF607D8B)
val PurpleGrey80 = Color(0xFFECEFF1)
val Pink80 = Color(0xFFCFD8DC)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val Gray = Color(0xFF607D8B)
val GrayLight = Color(0xFFB0BEC5)
val GrayDark = Color(0xFFECEFF1)

val Red = Color(0xFF37474F)
val Green = Color(0xFF546E7A)
val Blue = Color(0xFFECEFF1)

val md_theme_light_primary = Color(0xFF006783)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBDE9FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001F2A)
val md_theme_light_secondary = Color(0xFF4D616C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD0E6F2)
val md_theme_light_onSecondaryContainer = Color(0xFF081E27)
val md_theme_light_tertiary = Color(0xFF00677E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFB4EBFF)
val md_theme_light_onTertiaryContainer = Color(0xFF001F28)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFCFE)
val md_theme_light_onBackground = Color(0xFF191C1E)
val md_theme_light_surface = Color(0xFFFBFCFE)
val md_theme_light_onSurface = Color(0xFF191C1E)
val md_theme_light_surfaceVariant = Color(0xFFDCE4E9)
val md_theme_light_onSurfaceVariant = Color(0xFF40484C)
val md_theme_light_outline = Color(0xFF70787D)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F3)
val md_theme_light_inverseSurface = Color(0xFF2E3132)
val md_theme_light_inversePrimary = Color(0xFF65D3FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006783)
val md_theme_light_outlineVariant = Color(0xFFC0C8CD)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF65D3FF)
val md_theme_dark_onPrimary = Color(0xFF003546)
val md_theme_dark_primaryContainer = Color(0xFF004D64)
val md_theme_dark_onPrimaryContainer = Color(0xFFBDE9FF)
val md_theme_dark_secondary = Color(0xFFB4CAD6)
val md_theme_dark_onSecondary = Color(0xFF1F333C)
val md_theme_dark_secondaryContainer = Color(0xFF354A53)
val md_theme_dark_onSecondaryContainer = Color(0xFFD0E6F2)
val md_theme_dark_tertiary = Color(0xFF5AD5F9)
val md_theme_dark_onTertiary = Color(0xFF003542)
val md_theme_dark_tertiaryContainer = Color(0xFF004E5F)
val md_theme_dark_onTertiaryContainer = Color(0xFFB4EBFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1E)
val md_theme_dark_onBackground = Color(0xFFE1E2E4)
val md_theme_dark_surface = Color(0xFF191C1E)
val md_theme_dark_onSurface = Color(0xFFE1E2E4)
val md_theme_dark_surfaceVariant = Color(0xFF40484C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C8CD)
val md_theme_dark_outline = Color(0xFF8A9297)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1E)
val md_theme_dark_inverseSurface = Color(0xFFE1E2E4)
val md_theme_dark_inversePrimary = Color(0xFF006783)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF65D3FF)
val md_theme_dark_outlineVariant = Color(0xFF40484C)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF607D8B)
val CustomColor1 = Color(0xFF607D8B)
val CustomColor2 = Color(0xFFB0BEC5)
val CustomColor3 = Color(0xFFECEFF1)
val light_CustomColor1 = Color(0xFF006783)
val light_onCustomColor1 = Color(0xFFFFFFFF)
val light_CustomColor1Container = Color(0xFFBDE9FF)
val light_onCustomColor1Container = Color(0xFF001F2A)
val dark_CustomColor1 = Color(0xFF65D3FF)
val dark_onCustomColor1 = Color(0xFF003546)
val dark_CustomColor1Container = Color(0xFF004D64)
val dark_onCustomColor1Container = Color(0xFFBDE9FF)
val light_CustomColor2 = Color(0xFF006781)
val light_onCustomColor2 = Color(0xFFFFFFFF)
val light_CustomColor2Container = Color(0xFFB9EAFF)
val light_onCustomColor2Container = Color(0xFF001F29)
val dark_CustomColor2 = Color(0xFF5FD4FD)
val dark_onCustomColor2 = Color(0xFF003544)
val dark_CustomColor2Container = Color(0xFF004D62)
val dark_onCustomColor2Container = Color(0xFFB9EAFF)
val light_CustomColor3 = Color(0xFF00677E)
val light_onCustomColor3 = Color(0xFFFFFFFF)
val light_CustomColor3Container = Color(0xFFB4EBFF)
val light_onCustomColor3Container = Color(0xFF001F28)
val dark_CustomColor3 = Color(0xFF5AD5F9)
val dark_onCustomColor3 = Color(0xFF003542)
val dark_CustomColor3Container = Color(0xFF004E5F)
val dark_onCustomColor3Container = Color(0xFFB4EBFF)
